# These are supported funding model platforms

github: [funilrys] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: mitchellkrog # Replace with a single Ko-fi username
