# Build Script for Phishing Database using GHA

name: CI

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python V3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install domain2idna
          pip install PyFunceble-dev
          pip install ultimate-hosts-blacklist-whitelist


      - name: Run build
        shell: bash
        run: ./scripts/travis-commit.sh

